package com.greendev.bebekninnileri;

import java.util.ArrayList;

public class SongCreator {
    public static ArrayList<String> simdiOkulluOlduk() {
        ArrayList<String> noteTypes = new ArrayList();
        noteTypes.add("DO");
        noteTypes.add("DO");
        noteTypes.add("SOL");
        noteTypes.add("SOL");
        noteTypes.add("LA");
        noteTypes.add("LA");
        noteTypes.add("SOL");
        noteTypes.add("FA");
        noteTypes.add("FA");
        noteTypes.add("MI");
        noteTypes.add("MI");
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("DO");
        noteTypes.add("DO");
        noteTypes.add("DO");
        noteTypes.add("SOL");
        noteTypes.add("SOL");
        noteTypes.add("LA");
        noteTypes.add("LA");
        noteTypes.add("SOL");
        noteTypes.add("FA");
        noteTypes.add("FA");
        noteTypes.add("MI");
        noteTypes.add("MI");
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("DO");
        noteTypes.add("SOL");
        noteTypes.add("SOL");
        noteTypes.add("FA");
        noteTypes.add("FA");
        noteTypes.add("MI");
        noteTypes.add("MI");
        noteTypes.add("RE");
        noteTypes.add("SOL");
        noteTypes.add("SOL");
        noteTypes.add("FA");
        noteTypes.add("FA");
        noteTypes.add("MI");
        noteTypes.add("MI");
        noteTypes.add("RE");
        noteTypes.add("DO");
        noteTypes.add("DO");
        noteTypes.add("SOL");
        noteTypes.add("SOL");
        noteTypes.add("LA");
        noteTypes.add("LA");
        noteTypes.add("SOL");
        noteTypes.add("FA");
        noteTypes.add("FA");
        noteTypes.add("MI");
        noteTypes.add("MI");
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("DO");
        return noteTypes;
    }

    public static ArrayList<String> kucukKurbaga() {
        ArrayList<String> noteTypes = new ArrayList();
        noteTypes.add("SOL");
        noteTypes.add("MI");
        noteTypes.add("MI");
        noteTypes.add("MI");
        noteTypes.add("SOL");
        noteTypes.add("MI");
        noteTypes.add("MI");
        noteTypes.add("MI");
        noteTypes.add("SOL");
        noteTypes.add("LA");
        noteTypes.add("SOL");
        noteTypes.add("MI");
        noteTypes.add("FA");
        noteTypes.add("RE");
        noteTypes.add("FA");
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("FA");
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("FA");
        noteTypes.add("SOL");
        noteTypes.add("MI");
        noteTypes.add("RE");
        noteTypes.add("DO");
        noteTypes.add("FA");
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("FA");
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("FA");
        noteTypes.add("SOL");
        noteTypes.add("MI");
        noteTypes.add("RE");
        noteTypes.add("DO");
        return noteTypes;
    }

    public static ArrayList<String> neseliOlKiGenc() {
        ArrayList<String> noteTypes = new ArrayList();
        noteTypes.add("DO");
        noteTypes.add("DO");
        noteTypes.add("RE");
        noteTypes.add("MI");
        noteTypes.add("MI");
        noteTypes.add("RE");
        noteTypes.add("DO");
        noteTypes.add("RE");
        noteTypes.add("MI");
        noteTypes.add("DO");
        noteTypes.add("MI");
        noteTypes.add("MI");
        noteTypes.add("FA");
        noteTypes.add("SOL");
        noteTypes.add("SOL");
        noteTypes.add("FA");
        noteTypes.add("MI");
        noteTypes.add("FA");
        noteTypes.add("SOL");
        noteTypes.add("MI");
        noteTypes.add("SOL");
        noteTypes.add("SOL");
        noteTypes.add("LA");
        noteTypes.add("LA");
        noteTypes.add("FA");
        noteTypes.add("MI");
        noteTypes.add("FA");
        noteTypes.add("MI");
        noteTypes.add("SOL");
        noteTypes.add("SOL");
        noteTypes.add("DO");
        noteTypes.add("DO");
        noteTypes.add("RE");
        noteTypes.add("MI");
        noteTypes.add("MI");
        noteTypes.add("RE");
        noteTypes.add("DO");
        noteTypes.add("RE");
        noteTypes.add("MI");
        noteTypes.add("DO");
        return noteTypes;
    }

    public static ArrayList<String> bakPostaciGeliyor() {
        ArrayList<String> noteTypes = new ArrayList();
        noteTypes.add("SOL");
        noteTypes.add("FA");
        noteTypes.add("SOL");
        noteTypes.add("LA");
        noteTypes.add("SOL");
        noteTypes.add("FA");
        noteTypes.add("MI");
        noteTypes.add("RE");
        noteTypes.add("FA");
        noteTypes.add("MI");
        noteTypes.add("RE");
        noteTypes.add("SOL");
        noteTypes.add("FA");
        noteTypes.add("SOL");
        noteTypes.add("LA");
        noteTypes.add("SOL");
        noteTypes.add("FA");
        noteTypes.add("MI");
        noteTypes.add("RE");
        noteTypes.add("FA");
        noteTypes.add("MI");
        noteTypes.add("RE");
        noteTypes.add("DO");
        noteTypes.add("RE");
        return noteTypes;
    }

    public static ArrayList<String> kutuKutuPense() {
        ArrayList<String> noteTypes = new ArrayList();
        noteTypes.add("DO");
        noteTypes.add("RE");
        noteTypes.add("DO");
        noteTypes.add("RE");
        noteTypes.add("MI");
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("DO");
        noteTypes.add("RE");
        noteTypes.add("MI");
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("DO");
        noteTypes.add("SI");
        noteTypes.add("LA");
        noteTypes.add("SOL");
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("DO");
        noteTypes.add("SI");
        noteTypes.add("LA");
        noteTypes.add("SOL");
        noteTypes.add("SOL");
        return noteTypes;
    }

    public static ArrayList<String> yasasinOkulumuz() {
        ArrayList<String> noteTypes = new ArrayList();
        noteTypes.add("SOL");
        noteTypes.add("SOL");
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("MI");
        noteTypes.add("MI");
        noteTypes.add("RE");
        noteTypes.add("DO");
        noteTypes.add("DO");
        noteTypes.add("SI");
        noteTypes.add("SI");
        noteTypes.add("LA");
        noteTypes.add("LA");
        noteTypes.add("SOL");
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("DO");
        noteTypes.add("DO");
        noteTypes.add("SI");
        noteTypes.add("SI");
        noteTypes.add("LA");
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("DO");
        noteTypes.add("DO");
        noteTypes.add("SI");
        noteTypes.add("SI");
        noteTypes.add("LA");
        noteTypes.add("SOL");
        noteTypes.add("SOL");
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("MI");
        noteTypes.add("MI");
        noteTypes.add("RE");
        noteTypes.add("DO");
        noteTypes.add("DO");
        noteTypes.add("SI");
        noteTypes.add("SI");
        noteTypes.add("LA");
        noteTypes.add("LA");
        noteTypes.add("SOL");
        return noteTypes;
    }

    public static ArrayList<String> sutIctimDilimYandi() {
        ArrayList<String> noteTypes = new ArrayList();
        noteTypes.add("LA");
        noteTypes.add("SI");
        noteTypes.add("DO");
        noteTypes.add("RE");
        noteTypes.add("DO");
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("DO");
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("DO");
        noteTypes.add("SI");
        noteTypes.add("LA");
        noteTypes.add("SI");
        noteTypes.add("DO");
        noteTypes.add("RE");
        noteTypes.add("SI");
        noteTypes.add("DO");
        noteTypes.add("LA");
        noteTypes.add("SI");
        noteTypes.add("SOL");
        noteTypes.add("SOL");
        noteTypes.add("DO");
        noteTypes.add("SI");
        noteTypes.add("LA");
        return noteTypes;
    }

    public static ArrayList<String> trenGelirHosGelir() {
        ArrayList<String> noteTypes = new ArrayList();
        noteTypes.add("RE");
        noteTypes.add("RE");
        noteTypes.add("LA");
        noteTypes.add("LA");
        noteTypes.add("RE");
        noteTypes.add("LA");
        noteTypes.add("LA");
        noteTypes.add("DO");
        noteTypes.add("RE");
        noteTypes.add("DO");
        noteTypes.add("SI");
        noteTypes.add("LA");
        noteTypes.add("DO");
        noteTypes.add("DO");
        noteTypes.add("LA");
        noteTypes.add("LA");
        noteTypes.add("DO");
        noteTypes.add("DO");
        noteTypes.add("SI");
        noteTypes.add("DO");
        noteTypes.add("RE");
        noteTypes.add("SI");
        noteTypes.add("DO");
        noteTypes.add("SI");
        noteTypes.add("LA");
        noteTypes.add("LA");
        return noteTypes;
    }

    public static ArrayList<String> fisFisKayikci() {
        ArrayList<String> noteTypes = new ArrayList();
        noteTypes.add("LA");
        noteTypes.add("SOL");
        noteTypes.add("LA");
        noteTypes.add("LA");
        noteTypes.add("FA");
        noteTypes.add("SOL");
        noteTypes.add("FA");
        noteTypes.add("SOL");
        noteTypes.add("LA");
        noteTypes.add("LA");
        noteTypes.add("SOL");
        return noteTypes;
    }

    public static ArrayList<String> yagSatarimBalSatarim() {
        ArrayList<String> noteTypes = new ArrayList();
        noteTypes.add("LA");
        noteTypes.add("LA");
        noteTypes.add("LA");
        noteTypes.add("SOL");
        noteTypes.add("LA");
        noteTypes.add("LA");
        noteTypes.add("LA");
        noteTypes.add("SOL");
        noteTypes.add("FA");
        noteTypes.add("SOL");
        noteTypes.add("FA");
        noteTypes.add("SOL");
        noteTypes.add("LA");
        noteTypes.add("LA");
        noteTypes.add("LA");
        noteTypes.add("SOL");
        return noteTypes;
    }
}
